#!/bin/bash                                                                      
set -e                                                                           
printf 'Updating your PowerShell settings'         
../InstallProfile.ps1